In [2]:
import numpy as np
import pandas as pd
from math import sqrt

Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):

zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].

Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [3]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [4]:
cov1 = (zp*ks).mean() - zp.mean() * ks.mean()
cov1

9157.839999999997

In [9]:
cov2 =  np.cov(zp, ks, ddof=0)
cov2

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [11]:
std_zp = np.std(zp)
std_zp

59.115480206118605

In [18]:
std_ks = np.std(ks)
std_ks

174.55340157098058

In [21]:
Pirs_1 = cov2/(std_zp*std_ks)
Pirs_1

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

In [22]:
Pirs_2 = np.corrcoef(zp, ks)
Pirs_2

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:

131, 125, 115, 122, 131, 115, 107, 99, 125, 111.

Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [13]:
A = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
n = 10
T = 2.262

In [14]:
M = np.mean(A)
M

118.1

In [15]:
vari = A.var(ddof=1)
std = (vari)**0.5
std

10.54566788359614

In [16]:
T_1 = M - T * std/sqrt(n) # нижняя граница доверительного интервала
T_2 = M + T * std/sqrt(n) # верхняя граница доверительного интервала
print(T_1, T_2)

110.55660776308164 125.64339223691834


Известно, что рост футболистов в сборной распределен нормально с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27, среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [17]:
Z = 1.96
std = 5
M =  174.2
n = 27

T1 = M - Z * std / sqrt(n) # нижняя граница доверительного интервала
T2 = M + Z * std / sqrt(n) # верхняя граница доверительного интервала
print(T1, T2)

172.31398912064722 176.08601087935276


Выберите тему для проектной работы по курсу Теории вероятностей и математической статистики и напишите ее в комментарии к Практическому заданию.

In [18]:
#отправляю задание сейчас, по курсовому еще подумаю, пока непонятно за что браться и как строить работу :) если надумаю тему для согласования отправлю в ЛС